version: '3.8'

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_MYSQL_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "${DB_SQL_PORT}:${DB_SQL_PORT}"

  redis:
    image: redis:6
    ports:
      - "${DB_REDIS_PORT}:${DB_REDIS_PORT}"

  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:${DB_KAFKA_PORT}
    ports:
      - "${DB_KAFKA_PORT}:${DB_KAFKA_PORT}"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
